# Generated by Django 5.0.2 on 2024-03-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="painting_type_Db",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="paintings_Db",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=20, null=True)),
                ("pname", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="Images"),
                ),
                ("price", models.IntegerField(blank=True, null=True)),
                (
                    "picture_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=20, null=True)),
                ("description", models.CharField(blank=True, max_length=20, null=True)),
                ("no_copies", models.IntegerField(blank=True, null=True)),
                ("artist_name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "artist_picture",
                    models.ImageField(
                        blank=True,
                        default="Images/usericon11.png",
                        null=True,
                        upload_to="Images",
                    ),
                ),
            ],
        ),
    ]
