# Generated by Django 5.0.3 on 2024-03-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact_Db",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=20, null=True)),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=30, null=True)),
                ("phone", models.IntegerField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=20, null=True)),
                ("message", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
