# Generated by Django 5.0.3 on 2024-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0002_contact_db"),
    ]

    operations = [
        migrations.CreateModel(
            name="artist_Db",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="Images"),
                ),
                ("quote", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
