# Generated by Django 5.0.3 on 2024-03-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0003_artist_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist_db",
            name="link",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
