# Generated by Django 5.0.3 on 2024-03-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0004_artist_db_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist_db",
            name="quote",
        ),
    ]
