# Generated by Django 5.0.3 on 2024-03-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0005_remove_artist_db_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist_db",
            name="year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
