# Generated by Django 5.0.3 on 2024-03-21 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0006_artist_db_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "minimum_price",
                    models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="paintings_db",
            name="artist_picture",
            field=models.ImageField(
                blank=True,
                default="../Images/usericon11.png",
                null=True,
                upload_to="Images",
            ),
        ),
        migrations.CreateModel(
            name="AppliedCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(blank=True, max_length=100, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BackEnd.coupondb",
                    ),
                ),
            ],
        ),
    ]
