# Generated by Django 5.0.3 on 2024-03-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0007_coupondb_alter_paintings_db_artist_picture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artclasses_Db",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mainimage",
                    models.ImageField(blank=True, null=True, upload_to="Images"),
                ),
                (
                    "mainiheading",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="Images"),
                ),
                (
                    "subheading1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("link1", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="Images"),
                ),
                (
                    "subheading2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("link2", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="Images"),
                ),
                (
                    "subheading3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("link3", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "image4",
                    models.ImageField(blank=True, null=True, upload_to="Images"),
                ),
                (
                    "subheading4",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("link4", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description4",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "image5",
                    models.ImageField(blank=True, null=True, upload_to="Images"),
                ),
                (
                    "subheading5",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("link5", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description5",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
