# Generated by Django 5.0.3 on 2024-04-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0009_rename_mainiheading_artclasses_db_mainheading"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcoupon",
            name="discounted_amount",
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="appliedcoupon",
            name="totalprice",
            field=models.IntegerField(null=True),
        ),
    ]
