# Generated by Django 5.0.3 on 2024-04-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0011_coupondb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintings_db',
            name='status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], max_length=50, null=True),
        ),
    ]
