# Generated by Django 5.0.3 on 2024-04-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0012_paintings_db_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintings_db',
            name='status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], default='In Stock', max_length=50),
        ),
    ]
