# Generated by Django 5.0.2 on 2024-03-10 11:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("BackEnd", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(blank=True, max_length=200)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("mobile", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=200)),
                ("hobby", models.CharField(blank=True, max_length=200)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        default="media/Images/default.jpg",
                        null=True,
                        upload_to="Images",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SignUp_Db",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "Username",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("Password", models.CharField(blank=True, max_length=100, null=True)),
                ("Cpassword", models.CharField(blank=True, max_length=100, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "password_reset_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("token_expiration", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100, null=True)),
                ("lastname", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=200)),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                (
                    "phone",
                    models.CharField(
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Mobile number should only contain digits",
                                regex="^\\d+$",
                            )
                        ],
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Hubli", "Hubli"),
                            ("Banglore", "Banglore"),
                            ("Ernakulam", "Ernakulam"),
                            ("Hydrabad", "Hydrabad"),
                            ("Kannur", "Kannur"),
                            ("Coimbator", "Coimbator"),
                            ("Madurai", "Madurai"),
                            ("Thiruvananthapuram", "Thiruvananthapuram"),
                            ("Kozhikkode", "Kozhikkode"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Kerala", "Kerala"),
                            ("Tamilnadu", "Tamilnadu"),
                            ("Karnataka", "Karnataka"),
                            ("AndraPradesh", "AndraPradesh"),
                        ],
                        max_length=255,
                    ),
                ),
                ("pincode", models.PositiveIntegerField(blank=True, null=True)),
                ("default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(blank=True, max_length=100, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("tprice", models.IntegerField(blank=True, null=True)),
                (
                    "painting",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="BackEnd.paintings_db",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WishlistDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BackEnd.paintings_db",
                    ),
                ),
            ],
        ),
    ]
