# Generated by Django 5.0.2 on 2024-03-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FrontEnd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(
                choices=[
                    ("Banglore", "Banglore"),
                    ("Madurai", "Madurai"),
                    ("Kozhikkode", "Kozhikkode"),
                    ("Kannur", "Kannur"),
                    ("Ernakulam", "Ernakulam"),
                    ("Coimbator", "Coimbator"),
                    ("Thiruvananthapuram", "Thiruvananthapuram"),
                    ("Hubli", "Hubli"),
                    ("Hydrabad", "Hydrabad"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="Images/usericon1.png",
                null=True,
                upload_to="Images",
            ),
        ),
    ]
