# Generated by Django 5.0.3 on 2024-03-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FrontEnd", "0002_alter_address_city_alter_profile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="user",
        ),
        migrations.AddField(
            model_name="address",
            name="Username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="pincode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
