# Generated by Django 5.0.3 on 2024-03-13 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FrontEnd", "0003_remove_address_user_address_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=100)),
                ("order_total", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Order Confirmed", "Order Confirmed"),
                            ("Shipped", "Shipped"),
                            ("Out for delivery", "Out for delivery"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                            ("Returned", "Returned"),
                        ],
                        default="Order Confirmed",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FrontEnd.address",
                    ),
                ),
                (
                    "product_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FrontEnd.cartdb",
                    ),
                ),
            ],
        ),
    ]
