# Generated by Django 5.0.3 on 2024-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FrontEnd", "0004_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_mode",
            field=models.CharField(default="COD", max_length=50),
        ),
    ]
