# Generated by Django 5.0.3 on 2024-03-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FrontEnd", "0005_order_payment_mode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
