# Generated by Django 5.0.3 on 2024-03-13 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FrontEnd", "0008_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shipping", models.DecimalField(decimal_places=2, max_digits=10)),
                ("grand_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_to_be_paid",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payment_method", models.CharField(max_length=50)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Order Confirmed", "Order Confirmed"),
                            ("Shipped", "Shipped"),
                            ("Out for delivery", "Out for delivery"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                            ("Returned", "Returned"),
                        ],
                        default="Order Confirmed",
                        max_length=50,
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FrontEnd.address",
                    ),
                ),
            ],
        ),
    ]
