# Generated by Django 5.0.3 on 2024-03-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FrontEnd", "0009_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount_to_be_paid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="grand_total",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
