# Generated by Django 5.0.3 on 2024-03-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FrontEnd", "0010_alter_order_amount_to_be_paid_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
