# Generated by Django 5.0.3 on 2024-03-13 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FrontEnd", "0011_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.IntegerField(blank=True, null=True)),
                ("shipping", models.IntegerField(blank=True, null=True)),
                ("grand_total", models.IntegerField(blank=True, null=True)),
                ("amount_to_be_paid", models.IntegerField(blank=True, null=True)),
                ("payment_method", models.CharField(max_length=50)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Order Confirmed", "Order Confirmed"),
                            ("Shipped", "Shipped"),
                            ("Out for delivery", "Out for delivery"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                            ("Returned", "Returned"),
                        ],
                        default="Order Confirmed",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order_id", models.CharField(max_length=100, unique=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FrontEnd.address",
                    ),
                ),
            ],
        ),
    ]
