# Generated by Django 5.0.3 on 2024-03-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FrontEnd", "0012_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
