# Generated by Django 5.0.3 on 2024-03-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0007_coupondb_alter_paintings_db_artist_picture_and_more"),
        ("FrontEnd", "0013_order_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                ("total_price", models.IntegerField(null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="FrontEnd.order"
                    ),
                ),
                (
                    "painting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BackEnd.paintings_db",
                    ),
                ),
            ],
        ),
    ]
