# Generated by Django 5.0.3 on 2024-04-04 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0011_coupondb_status"),
        ("FrontEnd", "0016_subscription_db"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="painting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="BackEnd.paintings_db",
            ),
        ),
    ]
