# Generated by Django 5.0.3 on 2024-04-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FrontEnd", "0017_alter_orderitem_painting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="painting",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="Images"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="pname",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
