# Generated by Django 5.0.3 on 2024-04-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FrontEnd", "0018_remove_orderitem_painting_orderitem_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
